class Static:
    DESCRIPTION = 'description'
    INGREDIENTS = 'ingredients'
    DIRECTIONS = 'directions'
    REVIEWS = 'reviews'
    RATINGS = 'ratings'
    RELATED = 'related'
    TITLE = 'title'
    TAGS = 'categories'
    AUTHOR = 'author'
    DATEPUBLISHED = 'date-published'